const defaultData = {
  //this data is used to automatically generate the first row in the following tables.
  profileData: {
    first_name: null,
    last_name: null,
    profile_email: null,
    contact_num: null,
    council_reg_num: null,
  },
  practiceDetailsData: {
    practice_name: null,
    practice_num: null,
    practice_address: null,
    billing_address: null,
    profile_id: null,
  },
  defaultTitles: ["Dr.", "Mr.", "Mrs.", "Miss", "Ms.", "Master"],
  defaultHealthcareProfessions: [
    "Acupuncturist",
    "Allergist",
    "Anesthesiologist",
    "Audiologist",
    "Biokineticist",
    "Cardiologist",
    "Chiropractor",
    "Dentist",
    "Dermatologist",
    "Dietitian",
    "Emergency Medicine Specialist",
    "Endocrinologist",
    "Epidemiologist",
    "Gastroenterologist",
    "Geneticist",
    "Geriatrician",
    "Gynecologist",
    "Hematologist",
    "Immunologist",
    "Infectious Disease Specialist",
    "Internist",
    "Medical Geneticist",
    "Microbiologist",
    "Neonatologist",
    "Nephrologist",
    "Neurologist",
    "Neurosurgeon",
    "Nutritionist",
    "Obstetrician",
    "Occupational Therapist",
    "Oncologist",
    "Ophthalmologist",
    "Optometrist",
    "Orthodontist",
    "Orthopedic Surgeon",
    "Otolaryngologist",
    "Pathologist",
    "Pediatrician",
    "Pharmacist",
    "Physical Therapist",
    "Physician",
    "Plastic Surgeon",
    "Podiatrist",
    "Psychiatrist",
    "Psychologist",
    "Pulmonologist",
    "Radiologist",
    "Rheumatologist",
    "Speech Therapist",
    "Surgeon",
    "Urologist",
    "Veterinarian",
  ],
};

export default defaultData;
